// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euuuvmckdxzxdcjjgpwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1dXV2bWNrZHh6eGRjampncHdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3OTUwMDIsImV4cCI6MjA3MTM3MTAwMn0.mOfgkt2eikwLrgp604S7PM9Sx3PH6kpmedYJXHS4Dco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});